<AnimatedButtonScreen>:
    name: "animated"
    FloatLayout:
        size_hint: None, None


    DPEAButton:
        #Go back button (with an image)
        size: 175, 100
        text: "Back to main.py"
        text_color: 1, .5, 0 , 1
        center_x: root.width * 0.5
        center_y: root.height * 0.5
        color: 0.035, 0.52, 0.725, 1
        on_press: root.complexAnimation(self)
        size: 200, 200